export const PRODUCT_GET_REQUEST_SUCESSFULL = "PRODUCT_GET_REQUEST_SUCESSFULL";
export const PRODUCT_GET_REQUEST_LOADING = "PRODUCT_GET_REQUEST_LOADING";
export const PRODUCT_GET_REQUEST_FAILURE = "PRODUCT_GET_REQUEST_FAILURE";